### ISSUE TITLE
Compiling error with float*

### ISSUE THREAD

**Issue by WizzardMaker** [AdUki/LuaState#16]
I get the error:
In file included from ../Additional/i686-w64-mingw32/include/LuaState.h:36:0,
                 from Universal_System/Extensions/Lua/include.h:10,
                 from Universal_System/Extensions/Lua/lua.cpp:1:
../Additional/i686-w64-mingw32/include/./Traits.h: In instantiation of 'struct lua::traits::function_traits<float*>':
../Additional/i686-w64-mingw32/include/./LuaFunctor.h:108:85:   required from 'int lua::stack::push(lua_State_, T) [with T = float_; lua_State = lua_State]'
../Additional/i686-w64-mingw32/include/./LuaFunctor.h:59:47:   required from 'int lua::Functor<Ret, Args>::call(lua_State_) [with Ret = float_; Args = {float_, float_}; lua_State = lua_State]'
Universal_System/Extensions/Lua/lua.cpp:2213:1:   required from here
../Additional/i686-w64-mingw32/include/./Traits.h:17:39: error: 'operator()' is not a member of 'float*'
     : public function_traits<decltype(&T::operator())>

And I don't know why, is there something I am doing wrong?

**Comment by AdUki** [comment]
Probably you have older version of mingw which is not supported... What does `g++ -v` say?
If you have g++ version 4.8.1 and newer it should definitely work (I think even some older should work but now I don't know which ones).
If you g++ version is sufficient paste some code here...

**Comment by WizzardMaker** [comment]
g++ -v says that I use "4.8.1 (GCC)" and unfortunately  I cant really  post the Code because the whole function containing the error is about 5.000 lines full of extern function defining, and I eradicated (I deleted all float and used a lot of double or int instead) the problem a (long) time ago. I can try to find the problem again.
