### ISSUE TITLE
Is LuaState multithread?

### ISSUE THREAD

**Issue by micrenda** [AdUki/LuaState#17]
I am using LuaState in a multithread C++ aplication (using openmp). When calling any lua function I am forced to use pragma critical, otherwise I get segfaults.

I tried to use several LuaState's too, but I continue to get these segfaults. Was LuaState intended to be used in multithread context?

Regards

**Comment by fritzy** [comment]
LuaState, like lua.h underneath, is not multithreaded. You'll want to only access your lua context from a single thread.

**Comment by micrenda** [comment]
Thank you very much for your answer.
Regards
